### ISSUE TITLE
[sources] selected tab goes away on refresh

### ISSUE THREAD

**Issue by jasonLaster** [firefox-devtools/debugger.html#7708]
the pending selected location is cleared on refresh. This can be fixed by commenting out this code, which is not an ideal solution, but a start :)

```diff
diff --git a/src/actions/tabs.js b/src/actions/tabs.js
index 72bb7088e..8d4a1a44d 100644
--- a/src/actions/tabs.js
+++ b/src/actions/tabs.js
@@ -113,10 +113,10 @@ export function closeTabsForMissingThreads(workers: Worker[]) {
         }
       }
     }
-    const tabs = removeSourcesFromTabList(oldTabs, removed);
-    dispatch({ type: "CLOSE_TABS", removed, tabs });
-
-    const sourceId = getNewSelectedSourceId(getState(), tabs);
-    dispatch(selectSource(sourceId));
+    // const tabs = removeSourcesFromTabList(oldTabs, removed);
+    // dispatch({ type: "CLOSE_TABS", removed, tabs });
+    //
+    // const sourceId = getNewSelectedSourceId(getState(), tabs);
+    // dispatch(selectSource(sourceId));
   };
 }
```

**Comment by konradk** [comment]
Currently restoring tabs after reload doesn't work for me in development mode at all. Tabs are in the state, but `getSourcesForTabs` selector doesn't return them. It happens because `getSourceHelper` (reducers/sources.js) filters found sources and check it's thread: `source.thread == thread`. Source.thread is different with every reload (e.g. `server1.conn70.child1/context23`, after reload `server1.conn71.child1/context23`). I'm not sure what is correct logic there - this thread check should be changed somehow?

**Comment by errietta** [comment]
@jasonLaster I'm not sure that's still a thing, if it's about the open file tabs in 'sources', then I can see the selection after refreshing, also the code you mentioned appears to have changed

**Comment by jasonLaster** [comment]
interesting. i'll take a look
